# -*- coding: utf-8 -*-
"""Bản sao của Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MahKmdwGVjNaMkTM8EFCEF4OdfG5Hf8
"""

# 1. Cài đặt các thư viện cần thiết
!pip install roboflow ultralytics

from roboflow import Roboflow
rf = Roboflow(api_key="Q3GjE7RmvimYzxeMwqtL")
project = rf.workspace("tomisakae").project("pvz-bot-vision")
version = project.version(2)
dataset = version.download("yolov11")

# 3. Bắt đầu Train với YOLOv11 Nano (Bản nhẹ nhất)
from ultralytics import YOLO

# Load model v11n (nó sẽ tự tải về)
model = YOLO('yolo11n.pt')

# Train
results = model.train(
    data=f"{dataset.location}/data.yaml", # Trỏ vào data vừa tải
    epochs=100,      # Chạy 100 vòng (có thể giảm xuống 50 nếu muốn nhanh hơn)
    imgsz=640,       # Kích thước ảnh chuẩn
    batch=16,
    name='pvz_yolo11_run1' # Tên file kết quả
)

from ultralytics import YOLO

# Load cái model vừa train xong (run12)
model = YOLO('/content/runs/detect/pvz_yolo11_run12/weights/best.pt')

# Xuất sang OpenVINO (Tối ưu cho Intel CPU)
model.export(format='openvino')

# Nén thư mục model thành file zip để tải cho dễ
!zip -r pvz_model_openvino.zip /content/runs/detect/pvz_yolo11_run12/weights/best_openvino_model/